# This is a basic workflow to help you get started with Actions

name: Process Batches

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "run-batches"
  run-batches:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Python a one-line script
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install pandas boto3 openai torch transformers

      # Runs a set of commands using the runners shell
      - name: Run batch processor
        run: |
          echo "=== Starting batch processor ==="
          echo "Timestamp: $(date)"
          echo "Working directory: $(pwd)"
          
          # Run with explicit error handling
          set -e  # Exit on error
          set -x  # Print commands as they execute
          
          if ! python run_batches.py; then
            echo "❌ Script failed with exit code $?"
            echo "=== Checking for any output files ==="
            ls -la
            if [ -d "translations" ]; then
              echo "Contents of translations directory:"
              ls -la translations/
            fi
            exit 1
          else
            echo "✅ Script completed successfully"
          fi
        
      # Upload translations on success
      - name: Upload translation files
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: translation-results
          path: translations/
          if-no-files-found: warn
          
      # Upload debug info on failure  
      - name: Upload failure logs and debug info
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-info
          path: |
            translations/
            *.log
            *.txt
          if-no-files-found: ignore
          
      # Always upload the script itself for reference
      - name: Upload script for reference
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: source-script
          path: run_batches.py
          if-no-files-found: error
